vich_uploader:
  db_driver: orm

  mappings:
    medicalfiles:
      uri_prefix: '/files/medicaleFiles'
      upload_destination: '%kernel.project_dir%/public/files/medicaleFiles'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      namer: Vich\UploaderBundle\Naming\UniqidNamer